FROM node:8.12.0

RUN mkdir -p /app

WORKDIR /app

ADD package.json /app/

ADD package-lock.json /app/

COPY ./index.js /app/

COPY ./public /app/public

RUN npm install

EXPOSE 3000

CMD [ "node", "index.js" ]
