version: '2'
services:
  web_app:
    build:
      context: ./
      dockerfile: Dockerfile-web
    container_name: web_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:5.5
    build:
      context: ./
      dockerfile: Dockerfile-db
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
    - "3306"
